### ISSUE TITLE
How can i get Outlook tasks using this SDK?

### ISSUE THREAD

**Issue by karnshah8890** [microsoftgraph/android-java-snippets-sample#12]

**Comment by JohnMAustin78** [comment]
Outlook Tasks are not integrated into the Graph API. You still use the Outlook REST endpoint to get tasks. [Outlook tasks docs on MSDN](https://msdn.microsoft.com/en-us/office/office365/api/task-rest-operations)

**Comment by karnshah8890** [comment]
ok @JohnAustin-MSFT Thank you.

**Comment by karnshah8890** [comment]
@JohnAustin-MSFT When it will be available in Graph API?
