### ISSUE TITLE
signer information does not match signer information of other classes in the same package

### ISSUE THREAD

**Issue by ricalo** [microsoftgraph/android-java-snippets-sample#5]
@trevorwang, if this is the right repo, let's work on this issue instead of microsoftgraph/android-java-snippets-rest-sample#30

**Comment by ricalo** [comment]
I can't repro on this project either. Gradle just says that such task doesn't exist.
I'd like to take Android Studio out of the equation. What happens if you run (from a command line)?

```
./gradlew clean build
```

**Comment by trevorwang** [comment]
@Ricalo 

It works well from the command line

**Comment by ricalo** [comment]
Seems like a problem with **Instant Run** in your Android Studio installation. You can try disabling it for the project:
1. Go to **File** > **Settings** > **Build, Execution, Deployment** > **Debugger** > **Instant Run**
2. Uncheck **Enable Instant Run to hot swap code...**
3. Click **Apply**, Clean your project and try again.

You can also try to update your Android Studio installation. Let me know if this works.

**Comment by trevorwang** [comment]
It didn't work with studio 2.2 beta version but works well with studio 2.1.
Seems that android studio 2.2 beta has some issues.
Thanks very much for you quick response. @Ricalo

**Comment by ricalo** [comment]
I just updated to the stable version of Android Studio 2.2 and ran into this issue. Since this is the stable version, I'm reopening this bug.
However, seems to be out of the control of this repo and more related to AzureAD/azure-activedirectory-library-for-android#720.

I'll keep this open to keep track of the referenced issue. 

Thanks @trevorwang and @JohnAustin-MSFT

**Update:** The workaround, for now, is to ignore the dialog prompting you to update Gradle. Choose **Remind me later** or **Don't remind me again for this project** in the following dialog.

> To take advantage of all the latest features (such as Instant Run), improvements and security fixes, we strongly recommend that you update the Android Gradle plugin to version 2.2.0 and Gradle to version 2.14.1.

**Comment by headsvk** [comment]
You have 2 options now: if you want to use Instant Run, use Android Studio 2.1. If you don't need Instant Run use Android Studio 2.2 and keep gradle at v2.1.3.

**Comment by gauravgaikwad777** [comment]
There has to be some solution though, instant run is must have now a days

**Comment by ricalo** [comment]
Sorry for the late response, @gauravgaikwad777. I was on vacation.
Yes, there should be a solution, but it looks like it's on the ADAL team's side. Make sure to leave a comment in issue AzureAD/azure-activedirectory-library-for-android#720 to get their attention.

I'll close this issue for now, but will reopen in case there's an action item on this project.

**Comment by taraqr9** [comment]
> Seems like a problem with **Instant Run** in your Android Studio installation. You can try disabling it for the project:
> 
> 1. Go to **File** > **Settings** > **Build, Execution, Deployment** > **Debugger** > **Instant Run**
> 2. Uncheck **Enable Instant Run to hot swap code...**
> 3. Click **Apply**, Clean your project and try again.
> 
> You can also try to update your Android Studio installation. Let me know if this works.

Worked for me. Thank you so much
