### ISSUE TITLE
404 Error for Events Snippets

### ISSUE THREAD

**Issue by jvc56** [microsoftgraph/android-java-snippets-sample#9]
All of the snippets for groups run without errors, however, whenever I try to run any of the events snippets, this error is returned:

"GET https://graph.microsoft.com/v1.0/me/events
SdkVersion: graph-android-v1.1.0
Authorization: Bearer
eyJ0eXAiOiJKV1QiLCJub25jZSl[...]
SampleID: android-java-snippets-sample

404: Not Found
[...]

[Some information was truncated for brevity, enable debug logging for more details]"

I'm not sure why the group snippets would work but these wouldn't, it's probably a configuration issue on my end or something like that. I'm fairly new to this sort of stuff so thanks for the patience (for what's probably a trivial problem) and let me know if I need to post more information.

**Comment by JohnMAustin78** [comment]
Hi jvc,

Did you ever resolve the issue?  A 401 (unauthorized) error is the only 40x error I've seen on the events resource.  Even if you have no events, you'll still get an Events collection - no members. You should never get a 404.

John

**Comment by jvc56** [comment]
I've forgotten the details but I definitely resolved the issue somehow.

**Comment by jasonjoh** [comment]
Closing this issue as we are archiving this sample. Please see https://github.com/microsoftgraph/msgraph-training-android for an Android sample.
